#!/bin/sh /etc/rc.common

# adblock-oisd blocks ads using the highly popular oisd dnsmasq file and
# offers a simpler solution to adblocking than the bloated alternatives on OpenWrt

# Project homepage: https://github.com/lynxthecat/adblock-oisd

# Authors: @Lynx and @Wizballs and @colo (OpenWrt forum)

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

START=99
STOP=4

check_dnsmasq()
{
	if ! pgrep -x dnsmasq &> /dev/null
	then
		logger -p user.error -t adblock-oisd "No instance of dnsmasq detected."
		return 1
	fi

	for domain in google.com amazon.com microsoft.com
	do
		if ! nslookup -type=A "${domain}" \
			| awk -v st=1 '/^Address/{if(NR>2 && $2 ~ /^[0-9]+\.[0-9]+\.[0-9]+.[0-9]+$/){st=0}} END{exit st}'
		then
			logger -p user.error -t adblock-oisd "DNS A record lookup for >${domain}< failed to produce a result."
			return 1
		fi
	done
	return 0
}

start() 
{

	wget --timeout=60 --quiet -O- 'https://dnsmasq.oisd.nl/' | awk -F/ '
	BEGIN {
	  st=0
	  valid_bytes=0
	  recs=0
	  rogue=0
	  loginfo="logger -p user.info -t adblock-oisd"
	  logerror="logger -p user.error -t adblock-oisd"
	}

	/^(server|address)=/{
	  valid_bytes+=length($0)
          if(recs==0) {
	    print "Parsing oisd list data..." | loginfo
	  }
	  recs++
	  if(length($3) > 0) {
	    print "ERROR: Line " NR ": Bogus record? Data: " $0 | logerror
	    rogue++
	  } else {
	    printf("server=/%s/\n", $2)
	  }
	}

	END {
	  print "INFO: " valid_bytes " significant bytes in " recs " records (" NR " lines seen)" | loginfo
	  if(rogue > 0) {
	    print "FATAL: Bogus records: " rogue | logerror
	    st=1
	  }

	  if(recs < 10000) {
	    print "FATAL: Too few records in list: " recs | logerror
	    st=1
	  }

	  if(recs > 1000000) {
	    print "FATAL: Too many records in list: " recs | logerror
	    st=1
	  }

	  if(valid_bytes < 20000) {
	    print "FATAL: Too few valid bytes in list: " valid_bytes " bytes" | logerror
	    st=1
	  }

	  if(valid_bytes > 20000000) {
	    print "FATAL: List too long: " valid_bytes " bytes" | logerror
	    st=1
	  }

	  exit(st)
	}
	' > /tmp/oisd.txt

	if [ $? -ne 0 ]
	then
		logger -p user.error -t adblock-oisd "resulting blocklist file /tmp/oisd.txt failed basic sanity checks - bailing out."
		exit 1
	fi


	if [ -f /tmp/dnsmasq.d/oisd.txt ]
	then
		gzip -6 -c /tmp/dnsmasq.d/oisd.txt > /tmp/prev_oisd.txt.gz
	fi

	mv /tmp/oisd.txt /tmp/dnsmasq.d/oisd.txt

	logger -p user.info -t adblock-oisd "Restarting dnsmasq service..."
	/etc/init.d/dnsmasq restart &> /dev/null

	sleep 10

	if ! check_dnsmasq
	then
		logger -p user.error -t adblock-oisd "dnsmasq check failed with new oisd.txt file in place."
		rm /tmp/dnsmasq.d/oisd.txt

		if [ -f /tmp/prev_oisd.txt.gz ]
		then
			logger -p user.info -t adblock-oisd "Found previous oisd.txt file. Attempting to recover."
			gunzip -c /tmp/prev_oisd.txt.gz > /tmp/dnsmasq.d/oisd.txt
			rm -f /tmp/prev_oisd.txt.gz

			/etc/init.d/dnsmasq restart &> /dev/null			

			if ! check_dnsmasq
			then
				logger -p user.error -t adblock-oisd "dnsmasq check failed with previous oisd.txt file - stopping adblock-oisd."
				stop
			else
				logger -p user.warn -t adblock-oisd "previous oisd.txt recovered and dnsmasq check passed."
				exit 0
			fi
		else
			logger -p user.error -t adblock-oisd "No previous oisd.txt file found - stopping adblock-oisd"
			stop
		fi
		
	else
		rm -f /tmp/prev_oisd.txt.gz
	fi
}

stop()
{
	rm -f /tmp/dnsmasq.d/oisd.txt
	logger -p user.info -t adblock-oisd "Restarting dnsmasq service..."
	/etc/init.d/dnsmasq restart &> /dev/null
}
